# Generated by Django 3.0.4 on 2020-03-20 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todomodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='duedata',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
